// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TFG_Cultivos.Models;

#nullable disable

namespace TFG_Cultivos.Migrations
{
    [DbContext(typeof(PacContext))]
    partial class PacContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TFG_Cultivos.Models.DatoAgronomico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AireLibreProtegido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AñoCampaña")
                        .HasColumnType("integer");

                    b.Property<string>("CultivoPrincipalSecundario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EcoregimenPractica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EspecieVariedad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecintoId")
                        .HasColumnType("integer");

                    b.Property<string>("SecanoRegadio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SuperficieCultivada")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RecintoId");

                    b.ToTable("DatoAgronomico");
                });

            modelBuilder.Entity("TFG_Cultivos.Models.Parcelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAgregado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CodigoProvincia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ParcelaNumero")
                        .HasColumnType("integer");

                    b.Property<int>("Poligono")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("parcelas");
                });

            modelBuilder.Entity("TFG_Cultivos.Models.Recintos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdRecinto")
                        .HasColumnType("integer");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SuperficieSigpac")
                        .HasColumnType("numeric");

                    b.Property<string>("UsoSigpac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelaId");

                    b.ToTable("Recintos");
                });

            modelBuilder.Entity("TFG_Cultivos.Models.DatoAgronomico", b =>
                {
                    b.HasOne("TFG_Cultivos.Models.Recintos", "Recinto")
                        .WithMany("DatosAgronomicos")
                        .HasForeignKey("RecintoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recinto");
                });

            modelBuilder.Entity("TFG_Cultivos.Models.Recintos", b =>
                {
                    b.HasOne("TFG_Cultivos.Models.Parcelas", "Parcela")
                        .WithMany("Recintos")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcela");
                });

            modelBuilder.Entity("TFG_Cultivos.Models.Parcelas", b =>
                {
                    b.Navigation("Recintos");
                });

            modelBuilder.Entity("TFG_Cultivos.Models.Recintos", b =>
                {
                    b.Navigation("DatosAgronomicos");
                });
#pragma warning restore 612, 618
        }
    }
}
